// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbB9NrQH1q2XYmzJGmBrN_x3XDqA1a6tA',
    appId: '1:165519428953:web:d88c34730d6efdec73d048',
    messagingSenderId: '165519428953',
    projectId: 'boopee-app',
    authDomain: 'boopee-app.firebaseapp.com',
    storageBucket: 'boopee-app.appspot.com',
    measurementId: 'G-YKPESN5MTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzfeZfOx2GeiGNoieCCEy1E70V2MllJPM',
    appId: '1:165519428953:android:ca596068108b338973d048',
    messagingSenderId: '165519428953',
    projectId: 'boopee-app',
    storageBucket: 'boopee-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBroJBRRNtCoPeptDyEX14PwGxHqMVYUw0',
    appId: '1:165519428953:ios:62dd751dc539e14873d048',
    messagingSenderId: '165519428953',
    projectId: 'boopee-app',
    storageBucket: 'boopee-app.appspot.com',
    iosBundleId: 'com.example.boopee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBroJBRRNtCoPeptDyEX14PwGxHqMVYUw0',
    appId: '1:165519428953:ios:62dd751dc539e14873d048',
    messagingSenderId: '165519428953',
    projectId: 'boopee-app',
    storageBucket: 'boopee-app.appspot.com',
    iosBundleId: 'com.example.boopee',
  );
}
